# Travis-CI Build
# see travis-ci.org for details

language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.2.7"
  - MONO_VERSION="3.0.12"
  - MONO_VERSION="2.10.11"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.dmg"
 - hdid "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.dmg"
 - sudo installer -pkg "/Volumes/Mono Framework MDK ${MONO_VERSION}/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
 
script:
 - xbuild 
 - sh .ci/nunit.sh TravisTemplateForMono.Tests/bin/Debug/Tests.dll

# Notify development list when needed
notifications:
 recipients:
   - exkazuu@gmail.com
 email:
   on_success: change
   on_failure: always
